set -g default-shell /bin/zsh
set -g mouse on
setw -g xterm-keys on
set -s escape-time 0
set -g default-terminal "tmux-256color"
set -g set-clipboard on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g focus-events on
set -g history-limit 100000
bind r source-file ~/.tmux.conf \; display-message "Reloaded .tmux.conf"
set -gu update-environment PROMPT_NIX

setw -g mode-keys vi
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
